/* SPDX-License-Identifier: LGPL-2.1-or-later */
/*
 * libiio - Library for interfacing industrial I/O (IIO) devices
 *
 * Copyright (C) 2020 Analog Devices, Inc.
 */

#ifndef __IIO_BACKEND_H__
#define __IIO_BACKEND_H__

#include <stdbool.h>
#include <stdint.h>

struct iio_device;
struct iio_context;

enum iio_backend_api_ver {
	IIO_BACKEND_API_V1 = 1,
	IIO_BACKEND_API_V2 = 2,
	IIO_BACKEND_API_V3 = 3,
	IIO_BACKEND_API_V4 = 4,
	IIO_BACKEND_API_V5 = 5,
	IIO_BACKEND_API_V6 = 6,
};

#define IIO_BACKEND_API_CURRENT IIO_BACKEND_API_V6

static inline bool iio_backend_api_version_supported(unsigned int version)
{
	return version >= IIO_BACKEND_API_V1 &&
		version <= IIO_BACKEND_API_CURRENT;
}

enum iio_attr_type {
	IIO_ATTR_TYPE_DEVICE = 0,
	IIO_ATTR_TYPE_DEBUG,
	IIO_ATTR_TYPE_BUFFER,
};

struct iio_backend_ops {
	struct iio_context * (*clone)(const struct iio_context *ctx);
	ssize_t (*read)(const struct iio_device *dev, void *dst, size_t len,
			uint32_t *mask, size_t words);
	ssize_t (*write)(const struct iio_device *dev,
			const void *src, size_t len);
	int (*open)(const struct iio_device *dev,
			size_t samples_count, bool cyclic);
	int (*close)(const struct iio_device *dev);
	int (*get_fd)(const struct iio_device *dev);
	int (*set_blocking_mode)(const struct iio_device *dev, bool blocking);

	void (*cancel)(const struct iio_device *dev);

	int (*set_kernel_buffers_count)(const struct iio_device *dev,
			unsigned int nb_blocks);
	ssize_t (*get_buffer)(const struct iio_device *dev,
			void **addr_ptr, size_t bytes_used,
			uint32_t *mask, size_t words);

	ssize_t (*read_device_attr)(const struct iio_device *dev,
			const char *attr, char *dst, size_t len, enum iio_attr_type);
	ssize_t (*write_device_attr)(const struct iio_device *dev,
			const char *attr, const char *src,
			size_t len, enum iio_attr_type);
	ssize_t (*read_channel_attr)(const struct iio_channel *chn,
			const char *attr, char *dst, size_t len);
	ssize_t (*write_channel_attr)(const struct iio_channel *chn,
			const char *attr, const char *src, size_t len);

	int (*get_trigger)(const struct iio_device *dev,
			const struct iio_device **trigger);
	int (*set_trigger)(const struct iio_device *dev,
			const struct iio_device *trigger);

	void (*shutdown)(struct iio_context *ctx);

	int (*get_version)(const struct iio_context *ctx, unsigned int *major,
			unsigned int *minor, char git_tag[8]);

	int (*set_timeout)(struct iio_context *ctx, unsigned int timeout);

	/* API v3: required opaque request for capture-associated metadata. */
	int (*open_with_metadata)(const struct iio_device *dev,
			size_t samples_count, bool cyclic,
			const void *request, size_t request_bytes);
	ssize_t (*read_with_metadata)(const struct iio_device *dev,
			void *dst, size_t len, uint32_t *mask, size_t words,
			void *metadata, size_t metadata_capacity,
			size_t *metadata_bytes);
	ssize_t (*get_buffer_with_metadata)(const struct iio_device *dev,
			void **addr_ptr, size_t bytes_used,
			uint32_t *mask, size_t words,
			void *metadata, size_t metadata_capacity,
			size_t *metadata_bytes);

	/* API v4: prequeue existing metadata reads without changing their wire
	 * response. request_frames is nonzero for the first response in a bounded
	 * batch and zero while consuming the remaining prequeued responses. A v4
	 * backend exposing these operations must also expose cancel(). */
	ssize_t (*read_with_metadata_batch)(const struct iio_device *dev,
			void *dst, size_t len, uint32_t *mask, size_t words,
			void *metadata, size_t metadata_capacity,
			size_t *metadata_bytes, unsigned int request_frames);
	ssize_t (*get_buffer_with_metadata_batch)(const struct iio_device *dev,
			void **addr_ptr, size_t bytes_used,
			uint32_t *mask, size_t words,
			void *metadata, size_t metadata_capacity,
			size_t *metadata_bytes, unsigned int request_frames);

	/* API v5: retrieve the provider-owned status blob for an open metadata
	 * buffer without changing the refill stream. */
	ssize_t (*get_buffer_metadata_status)(const struct iio_device *dev,
			void *status, size_t status_capacity);

	/* API v6: start one bounded asynchronous metadata capture. Responses
	 * retain the ordinary READBUFM wire format. */
	int (*prequeue_metadata_reads_async)(const struct iio_device *dev,
			size_t len, size_t metadata_capacity,
			unsigned int frames);

	/* API v6: independently lease completed high-speed input blocks. */
	int (*acquire_buffer_block)(const struct iio_device *dev,
			void **addr, size_t *bytes_used, uintptr_t *token);
	int (*release_buffer_block)(const struct iio_device *dev,
			uintptr_t token, size_t bytes_used);
};

/**
 * struct iio_backend - IIO backend object (API version 1)
 * @api_version			API version for interfacing with libiio core library
 * @name			Name of this backend
 * @uri_prefix			URI prefix for this backend
 * @ops				Reference to backend ops
 * @sizeof_context_pdata	Size of private data for the IIO contexts generated by this backend
 */
struct iio_backend {
	unsigned int			api_version;
	const char			*name;
	const char			*uri_prefix;
	const struct iio_backend_ops	*ops;
	unsigned int			sizeof_context_pdata;
};

struct iio_context * iio_context_create_from_backend(
		const struct iio_backend *backend,
		const char *description);

#endif /* __IIO_BACKEND_H__ */
